services:
  db:
    image: postgres:16
    container_name: simplepos-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simplepos
    ports:
      - "5432:5432"
    volumes:
      - simplepos_pgdata:/var/lib/postgresql/data

volumes:
  simplepos_pgdata:
